# Generated by Django 4.1.7 on 2023-03-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_name', models.CharField(db_column='AGENT_NAME', max_length=100, primary_key=True, serialize=False)),
                ('agent_tel', models.CharField(db_column='AGENT_TEL', max_length=100)),
                ('agent_type', models.CharField(db_column='AGENT_TYPE', max_length=100)),
                ('use_yn', models.CharField(db_column='USE_YN', max_length=100)),
                ('entry_id', models.CharField(db_column='ENTRY_ID', max_length=20)),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE')),
                ('updat_id', models.CharField(blank=True, db_column='UPDAT_ID', max_length=20, null=True)),
                ('updat_date', models.DateTimeField(blank=True, db_column='UPDAT_DATE', null=True)),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
    ]
