# Generated by Django 4.1.7 on 2023-03-20 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_yn', models.CharField(db_column='USE_YN', max_length=100, verbose_name='사용여부')),
                ('entry_id', models.CharField(db_column='ENTRY_ID', max_length=20, verbose_name='등록자')),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE', verbose_name='등록일')),
                ('updat_id', models.CharField(blank=True, db_column='UPDAT_ID', max_length=20, null=True, verbose_name='수정자')),
                ('updat_date', models.DateTimeField(blank=True, db_column='UPDAT_DATE', null=True, verbose_name='수정일')),
                ('bank_name', models.CharField(db_column='BANK_NAME', max_length=100, verbose_name='은행명')),
                ('account_name', models.CharField(db_column='ACCOUNT_NAME', max_length=100, verbose_name='예금주')),
                ('account_no', models.CharField(db_column='ACCOUNT_NO', max_length=100, verbose_name='계좌번호')),
                ('swift', models.CharField(db_column='SWIFT', max_length=100, verbose_name='SWIFT')),
                ('iban_code', models.CharField(db_column='IBAN_CODE', max_length=100, verbose_name='IBAN_CODE')),
                ('branch', models.CharField(db_column='BRANCH', max_length=100, verbose_name='BRANCH')),
                ('bank_remark', models.TextField(db_column='BANK_REMARK', max_length=1000, verbose_name='REMARK')),
            ],
            options={
                'verbose_name': '은행',
                'verbose_name_plural': '은행 목록',
                'db_table': 'bank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_yn', models.CharField(db_column='USE_YN', max_length=100, verbose_name='사용여부')),
                ('entry_id', models.CharField(db_column='ENTRY_ID', max_length=20, verbose_name='등록자')),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE', verbose_name='등록일')),
                ('updat_id', models.CharField(blank=True, db_column='UPDAT_ID', max_length=20, null=True, verbose_name='수정자')),
                ('updat_date', models.DateTimeField(blank=True, db_column='UPDAT_DATE', null=True, verbose_name='수정일')),
                ('hotel_name', models.CharField(db_column='HOTEL_NAME', max_length=100, verbose_name='호텔명')),
                ('hotel_en_name', models.CharField(db_column='HOTEL_EN_NAME', max_length=100, verbose_name='호텔명(영어)')),
                ('rank', models.CharField(db_column='RANK', max_length=100, verbose_name='등급')),
                ('country', models.CharField(db_column='COUNTRY', max_length=100, verbose_name='국가')),
                ('city', models.CharField(db_column='CITY', max_length=100, verbose_name='도시')),
                ('address', models.CharField(db_column='ADDRESS', max_length=1000, verbose_name='주소')),
                ('hotel_tel', models.CharField(db_column='HOTEL_TEL', max_length=100, verbose_name='전화번호')),
                ('hotel_remark', models.TextField(db_column='HOTEL_REMARK', max_length=1000, verbose_name='REMARK')),
            ],
            options={
                'verbose_name': '호텔',
                'verbose_name_plural': '호텔 목록',
                'db_table': 'hotel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Traval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_yn', models.CharField(db_column='USE_YN', max_length=100, verbose_name='사용여부')),
                ('entry_id', models.CharField(db_column='ENTRY_ID', max_length=20, verbose_name='등록자')),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE', verbose_name='등록일')),
                ('updat_id', models.CharField(blank=True, db_column='UPDAT_ID', max_length=20, null=True, verbose_name='수정자')),
                ('updat_date', models.DateTimeField(blank=True, db_column='UPDAT_DATE', null=True, verbose_name='수정일')),
                ('traval_name', models.CharField(db_column='HOTEL_NAME', max_length=100, verbose_name='호텔명')),
                ('traval_en_name', models.CharField(db_column='HOTEL_EN_NAME', max_length=100, verbose_name='호텔명(영어)')),
                ('rank', models.CharField(db_column='RANK', max_length=100, verbose_name='등급')),
                ('country', models.CharField(db_column='COUNTRY', max_length=100, verbose_name='국가')),
                ('city', models.CharField(db_column='CITY', max_length=100, verbose_name='도시')),
                ('address', models.CharField(db_column='ADDRESS', max_length=1000, verbose_name='주소')),
                ('hotel_tel', models.CharField(db_column='HOTEL_TEL', max_length=100, verbose_name='전화번호')),
                ('hotel_remark', models.TextField(db_column='HOTEL_REMARK', max_length=1000, verbose_name='REMARK')),
            ],
            options={
                'verbose_name': '호텔',
                'verbose_name_plural': '호텔 목록',
                'db_table': 'traval',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScheduleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_yn', models.CharField(db_column='USE_YN', max_length=100, verbose_name='사용여부')),
                ('entry_id', models.CharField(db_column='ENTRY_ID', max_length=20, verbose_name='등록자')),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE', verbose_name='등록일')),
                ('updat_id', models.CharField(blank=True, db_column='UPDAT_ID', max_length=20, null=True, verbose_name='수정자')),
                ('updat_date', models.DateTimeField(blank=True, db_column='UPDAT_DATE', null=True, verbose_name='수정일')),
                ('product_name', models.CharField(db_column='PRODUCT_NAME', max_length=100, verbose_name='상품명')),
                ('location', models.CharField(db_column='LOCATION', max_length=100, verbose_name='지역')),
                ('start', models.CharField(db_column='START', max_length=100, verbose_name='출발지')),
                ('night', models.CharField(db_column='NIGHT', max_length=1000, verbose_name='박')),
                ('day', models.CharField(db_column='DAY', max_length=100, verbose_name='일')),
                ('bus', models.CharField(db_column='BUS', max_length=100, verbose_name='버스')),
                ('entrance', models.CharField(db_column='ENTRANCE', max_length=100, verbose_name='입장지')),
                ('breakfast', models.CharField(db_column='BREAKFAST', max_length=100, verbose_name='조식')),
                ('lunch', models.CharField(db_column='LUNCH', max_length=100, verbose_name='중식')),
                ('dinner', models.CharField(db_column='DINNER', max_length=100, verbose_name='석식')),
                ('special', models.CharField(db_column='SPECIAL', max_length=100, verbose_name='특식')),
                ('option', models.CharField(db_column='OPTION', max_length=100, verbose_name='옵션')),
                ('shopping', models.CharField(db_column='SHOPPING', max_length=100, verbose_name='쇼핑')),
                ('schedule_remark', models.TextField(db_column='SCHEDULE_REMARK', max_length=1000, verbose_name='REMARK')),
                ('agent', models.ForeignKey(blank=True, db_column='AGENT', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.agent', verbose_name='여행사')),
                ('manager', models.ForeignKey(blank=True, db_column='MANAGER', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.manager', verbose_name='담당자')),
            ],
            options={
                'verbose_name': '스케줄 마스터',
                'verbose_name_plural': '스케줄 마스터 목록',
                'db_table': 'schedule_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScheduleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_yn', models.CharField(db_column='USE_YN', max_length=100, verbose_name='사용여부')),
                ('entry_id', models.CharField(db_column='ENTRY_ID', max_length=20, verbose_name='등록자')),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE', verbose_name='등록일')),
                ('updat_id', models.CharField(blank=True, db_column='UPDAT_ID', max_length=20, null=True, verbose_name='수정자')),
                ('updat_date', models.DateTimeField(blank=True, db_column='UPDAT_DATE', null=True, verbose_name='수정일')),
                ('day', models.CharField(db_column='DAY', max_length=100, verbose_name='일차')),
                ('schedule', models.CharField(db_column='SCHEDULE', max_length=100, verbose_name='일정')),
                ('hotel', models.CharField(db_column='HOTEL', max_length=100, verbose_name='호텔')),
                ('master_id', models.ForeignKey(blank=True, db_column='MASTER_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.schedulemaster', verbose_name='마스터 ID')),
            ],
            options={
                'verbose_name': '스케줄 디테일',
                'verbose_name_plural': '스케줄 디테일 목록',
                'db_table': 'schedule_detail',
                'managed': True,
            },
        ),
    ]
